Peds\EntitiesBundle\Entity\Activity:
    type: entity
    table: activity
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        shortName:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: short_name
        description:
            type: text
            nullable: true
    manyToOne:
        rp:
            targetEntity: ReferenceProcess
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rp_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
