Peds\EntitiesBundle\Entity\OutputProducts:
    type: entity
    table: output_products
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        task:
            targetEntity: Task
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                task:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                product:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
