Peds\EntitiesBundle\Entity\Product:
    type: entity
    table: product
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        shortName:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: short_name
        description:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
