Peds\EntitiesBundle\Entity\TaskComp:
    type: entity
    table: task_comp
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        obs:
            type: text
            nullable: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        baseTask:
            targetEntity: Task
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                base_task_id:
                    referencedColumnName: id
            orphanRemoval: false
        rp:
            targetEntity: ReferenceProcess
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rp_id:
                    referencedColumnName: id
            orphanRemoval: false
        matching:
            targetEntity: Matching
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                matching_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
