peds_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PedsUserBundle:Default:index }
register:
    pattern:  /register2
    defaults: { _controller: PedsUserBundle:Register:index }
new_user:
    pattern:  /register
    defaults: { _controller: PedsUserBundle:Register:new }
user_mail:
    pattern:  /{_locale}/account/management/editE
    defaults: { _controller: PedsUserBundle:UserManagement:Mail, _locale: en  }
    requirements:
        _locale: en|es
user_edit_mail:
    pattern:  /{_locale}/account/management/editE/
    defaults: { _controller: PedsUserBundle:UserManagement:editMail, _locale: en  }
    requirements:
        _locale: en|es
user_pass:
    pattern:  /{_locale}/account/management/editP
    defaults: { _controller: PedsUserBundle:UserManagement:Pass, _locale: en  }
    requirements:
        _locale: en|es
user_edit_pass:
    pattern:  /{_locale}/account/management/editP/
    defaults: { _controller: PedsUserBundle:UserManagement:editPass, _locale: en  }
    requirements:
        _locale: en|es
