peds_account_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PedsAccountBundle:Default:index }
peds_account:
    pattern:  /{_locale}/account
    defaults: { _controller: PedsAccountBundle:Account:index, _locale: en }
    requirements:
        _locale: en|es
login:
    pattern:   /login
    defaults:  { _controller: PedsAccountBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
peds_matching:
    pattern:   /matching
    defaults:  { _controller: PedsAccountBundle:MantenedorMatching:index }
peds_matching_edit:
    pattern:   /matching/edit/{id}
    defaults:  { _controller: PedsAccountBundle:MantenedorMatching:edit }
peds_load_rp:
    pattern:   /{_locale}/load_rp
    defaults:  { _controller: PedsAccountBundle:LoadRP:index ,_locale: en}
    requirements:
        _locale: en|es
peds_load_rp_func:
    pattern:   /{_locale}/load_rp/
    defaults:  { _controller: PedsAccountBundle:LoadRP:load,locale: en }
    requirements:
        _locale: en|es
peds_text_excel_export:
    pattern:   /test/export
    defaults:  { _controller: PedsAccountBundle:TestExportExcel:index }
peds_text_excel_export_func:
    pattern:   /test/export/
    defaults:  { _controller: PedsAccountBundle:TestExportExcel:export }
peds_import_public_rp:
    pattern:   /import/rp
    defaults:  { _controller: PedsAccountBundle:ImportPublicRP:index }