parameters:
#    peds_account.example.class: Peds\AccountBundle\Example

services:
#    peds_account.example:
#        class: %peds_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
